"use client";

/** Design reminder — 日本語の情報密度を優先し、技術・作品・活動先を一画面で辿れる個人開発エンジニアのサイト。 */
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { SplashOverlay } from "./SplashOverlay";
import { YkMark } from "./YkMark";

type Category = "すべて" | "プロダクト" | "実験" | "記録";
type Social = "github" | "x" | "qiita";
type Glyph = "terminal" | "layers" | "spark" | "arrow" | "ship" | "pulse";

const filters: Category[] = ["すべて", "プロダクト", "実験", "記録"];
const projects = [{ id: "yohaku", category: "プロダクト" as const, index: "01", title: "YOHAKU", status: "公開中", kind: "匿名で言葉を残す場所", url: "https://yohaku-one.vercel.app/", description: "肩書きや反応数ではなく、書かれた言葉に集中できる匿名投稿サービス。企画、UI、実装まで一貫して制作しています。", stack: ["Next.js", "TypeScript", "Supabase"] }];
const socials: { label: string; kind: Social; url: string; handle: string }[] = [{ label: "GitHub", kind: "github", url: "https://github.com/Yuke-agc", handle: "@Yuke-agc" }, { label: "X", kind: "x", url: "https://x.com/Yuke_agc", handle: "@Yuke_agc" }, { label: "Qiita", kind: "qiita", url: "https://qiita.com/Yuke-agc", handle: "@Yuke-agc" }];

function SocialIcon({ kind }: { kind: Social }) {
  if (kind === "github") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.7a9.3 9.3 0 0 0-2.94 18.12c.47.09.64-.2.64-.45v-1.76c-2.62.57-3.17-1.12-3.17-1.12-.43-1.1-1.05-1.39-1.05-1.39-.86-.58.07-.57.07-.57.95.07 1.45.98 1.45.98.85 1.45 2.22 1.03 2.76.78.09-.61.33-1.03.6-1.27-2.09-.24-4.28-1.04-4.28-4.65 0-1.03.37-1.87.98-2.53-.1-.24-.43-1.2.09-2.5 0 0 .8-.26 2.56.97A8.9 8.9 0 0 1 12 7.2c.79 0 1.58.1 2.32.31 1.77-1.23 2.56-.97 2.56-.97.52 1.3.2 2.26.1 2.5.6.66.97 1.5.97 2.53 0 3.62-2.2 4.4-4.3 4.64.34.29.64.85.64 1.7v2.52c0 .25.17.55.65.45A9.3 9.3 0 0 0 12 2.7Z" /></svg>;
  if (kind === "x") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18.9 3H22l-6.77 7.74L23.2 21h-6.24l-4.89-6.4L6.47 21H3.35l7.24-8.28L2.95 3h6.4l4.42 5.84L18.9 3Zm-1.1 16.04h1.73L8.4 4.86H6.54L17.8 19.04Z" /></svg>;
  return <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="11" cy="11" r="7.2"/><path d="m15.9 15.9 4.1 4.1M8 11h6M11 8v6"/></svg>;
}
function Icon({ name }: { name: Glyph }) { const paths: Record<Glyph, React.ReactNode> = { terminal:<><path d="m5 7 4 4-4 4M12 16h7"/></>, layers:<><path d="m12 4 8 4-8 4-8-4 8-4ZM4 12l8 4 8-4M4 16l8 4 8-4"/></>, spark:<><path d="m12 3 1.6 5.4L19 10l-5.4 1.6L12 17l-1.6-5.4L5 10l5.4-1.6L12 3Z"/></>, arrow:<><path d="M5 12h14M13 6l6 6-6 6"/></>, ship:<><path d="M5 14h14l-2 5H7l-2-5ZM12 4v10M8 8h8"/></>, pulse:<><path d="M4 12h4l2-5 4 10 2-5h4"/></> }; return <svg className="system-icon" viewBox="0 0 24 24" fill="none" aria-hidden="true">{paths[name]}</svg>; }
function Label({ children }: { children: React.ReactNode }) { return <p className="label"><i/>{children}</p>; }

export function PortfolioExperience() {
  const [theme, setTheme] = useState<"light" | "dark">(() => typeof window !== "undefined" && window.localStorage.getItem("yk-theme") === "dark" ? "dark" : "light");
  const [activeFilter, setActiveFilter] = useState<Category>("すべて"); const [sent, setSent] = useState(false);
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  const visibleProjects = useMemo(() => projects.filter((project) => activeFilter === "すべて" || project.category === activeFilter), [activeFilter]);
  const toggleTheme = () => { const next = theme === "light" ? "dark" : "light"; setTheme(next); window.localStorage.setItem("yk-theme", next); };
  const createMail = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get("name") ?? ""); const email = String(data.get("email") ?? ""); const type = String(data.get("type") ?? ""); const scope = String(data.get("scope") ?? ""); const timing = String(data.get("timing") ?? "未定"); const budget = String(data.get("budget") ?? "未定"); setSent(true); window.location.href = `mailto:yuke.agc@gmail.com?subject=${encodeURIComponent(`お問い合わせ｜${type}｜${name}`)}&body=${encodeURIComponent(`お名前: ${name}\n返信先: ${email}\n相談内容: ${type}\n\n概要:\n${scope}\n\n希望時期: ${timing}\n予算感: ${budget}`)}`; };

  return <><SplashOverlay/><main className="engineer-shell">
    <header className="nav"><a href="#top" className="brand" aria-label="YUKE トップへ"><span className="brand-mark"><YkMark/></span><b>YUKE</b><small>個人開発エンジニア</small></a><nav aria-label="ページ内ナビゲーション"><a href="#build">つくるもの</a><a href="#system">つくり方</a><a href="#connect">つながる</a></nav><div className="nav-actions"><div className="social-mini">{socials.map((item)=><a key={item.kind} href={item.url} target="_blank" rel="noreferrer" aria-label={`${item.label}を開く`}><SocialIcon kind={item.kind}/></a>)}</div><button onClick={toggleTheme} className="theme" type="button" aria-label="配色テーマを切り替える"><i/>{theme === "light" ? "ダーク" : "ライト"}</button></div></header>

    <section id="top" className="hero"><div className="hero-copy"><Label>個人開発エンジニア / 東京</Label><h1>考えて、<br/><em>つくって、</em><br/>届ける。</h1><p>アイデアを、使えるプロダクトへ。企画、情報設計、インターフェース、実装までを一気通貫でつくっています。</p><div className="hero-cta"><a href="#build" className="cta cta-primary">作品を見る <Icon name="arrow"/></a><a href="#connect" className="cta cta-quiet">相談する <span>↗</span></a></div><div className="now-line"><span><i/> 現在公開中</span><b>YOHAKU — 匿名で言葉を残す場所</b><em>01 / 01</em></div></div><aside className="hero-signal"><div className="signal-grid"><i/><i/><i/><i/><i/><i/><i/><i/><div className="signal-mark"><YkMark/></div></div><div className="signal-info"><span>YUKE / SIGNAL</span><b>個人開発<br/>エンジニア</b><em>稼働中 <i/></em></div></aside><div className="hero-rail">スクロールして見る <i/></div></section>

    <section id="build" className="section releases"><div className="section-head"><Label>01 / 公開中のプロダクト</Label><div><h2>つくったもの。</h2><p>公開して、使われて、改善し続ける。今のプロダクトと開発中のアイデアです。</p></div><span>01—03</span></div><div className="filter-bar" role="toolbar" aria-label="プロダクトの絞り込み">{filters.map((filter)=>{const count=filter === "すべて" ? projects.length : projects.filter((p)=>p.category === filter).length;return <button key={filter} className={activeFilter===filter ? "active" : ""} onClick={()=>setActiveFilter(filter)} type="button">{filter}<b>{String(count).padStart(2,"0")}</b></button>})}</div><div className="release-grid">{visibleProjects.map((project)=><article className="release-card" key={project.id}><div className="release-meta"><span>{project.index} / {project.category}</span><b><i/> {project.status}</b></div><a className="release-visual" href={project.url} target="_blank" rel="noreferrer" aria-label={`${project.title}を開く`}><div className="terminal"><header><i/><i/><i/><span>yohaku.app</span></header><div><b>余</b><p>言葉だけを<br/>残せる場所</p><small>● 公開中のプロダクト</small></div></div><em>プロダクトを見る <strong>↗</strong></em></a><div className="release-title"><div><h3>{project.title}</h3><p>{project.kind}</p></div><Icon name="ship"/></div><p className="release-desc">{project.description}</p><ul>{project.stack.map((item)=><li key={item}>{item}</li>)}</ul></article>)}{!visibleProjects.length && <article className="empty-release"><Icon name="spark"/><h3>準備中です。</h3><p>このカテゴリの制作物は、現在準備中です。</p></article>}<article className="next-release"><span>次のプロダクト / 準備中</span><div><Icon name="terminal"/><h3>役に立つものを<br/>考えています。</h3></div><p>新しいアイデアを、小さく早く形にしています。</p><b>開発の記録を見る <Icon name="arrow"/></b></article></div></section>

    <section className="operator-strip"><span>考える</span><i/><span>設計する</span><i/><span>実装する</span><i/><span>届ける</span></section>
    <section id="system" className="section system"><div className="section-head"><Label>02 / つくり方</Label><div><h2>ものづくりの流れ。</h2><p>「つくる」前後の工程も含めて、一つのプロダクトとして扱います。</p></div><span>工程 / 04</span></div><div className="system-grid"><article><span>01</span><Icon name="spark"/><h3>課題を見つける</h3><p>誰の、どんな行動を変えるかを定め、つくる理由と最小の価値を見つけます。</p></article><article><span>02</span><Icon name="layers"/><h3>形を設計する</h3><p>情報と操作の順番を整理し、使う人が迷わない構造をつくります。</p></article><article><span>03</span><Icon name="terminal"/><h3>プロダクトにする</h3><p>型安全な実装と再利用できるUIで、動くプロダクトへ落とし込みます。</p></article><article><span>04</span><Icon name="pulse"/><h3>公開後も育てる</h3><p>公開後の反応を観察し、次の改善を小さく、継続的に積み重ねます。</p></article></div></section>
    <section className="section stack"><Label>03 / 技術と道具</Label><div className="stack-main"><h2>技術は、<br/><em>手段のひとつ。</em></h2><div><p>プロダクトの目的に合わせ、考え方と技術を選びます。</p><div className="stack-list"><span>TypeScript</span><span>Next.js</span><span>React</span><span>Supabase</span><span>Tailwind CSS</span><span>Figma</span></div><div className="stack-note"><Icon name="terminal"/><p>今、特に取り組んでいること：<b>小さなプロダクト、明快なUI、確実なリリース。</b></p></div></div></div></section>
    <section id="connect" className="connect"><div className="connect-copy"><Label>04 / つながる</Label><h2>次のアイデアを、<br/><em>形にしませんか。</em></h2><p>新しいプロダクト、既存サービスの改善、実装の相談。まだ曖昧な段階でも、まずは聞かせてください。</p><div className="social-list"><span>活動を追う</span>{socials.map((item)=><a key={item.kind} href={item.url} target="_blank" rel="noreferrer"><SocialIcon kind={item.kind}/><b>{item.label}</b><i>{item.handle}</i><em>↗</em></a>)}</div></div><form onSubmit={createMail} className="contact-form"><header><span>プロジェクトの相談</span><b><i/> 受付中</b></header><label>お名前<input name="name" required placeholder="山田 太郎"/></label><label>返信先メールアドレス<input name="email" type="email" required placeholder="you@example.com"/></label><label>相談したいこと<select name="type" required defaultValue=""><option value="" disabled>選択してください</option><option>新しいプロダクトをつくりたい</option><option>既存サービスを改善したい</option><option>ポートフォリオやサイトをつくりたい</option><option>実装について相談したい</option></select></label><label>プロジェクトの概要<textarea name="scope" rows={4} required placeholder="背景、実現したいこと、現在困っていることを教えてください。"/></label><div className="form-pair"><label>希望時期<select name="timing" defaultValue="未定・相談して決めたい"><option>未定・相談して決めたい</option><option>できるだけ早く</option><option>1か月以内</option><option>3か月以内</option></select></label><label>予算感<select name="budget" defaultValue="未定・相談して決めたい"><option>未定・相談して決めたい</option><option>〜10万円</option><option>10〜30万円</option><option>30万円〜</option></select></label></div><button type="submit">メールを作成する <span>↗</span></button><p aria-live="polite">{sent ? "メールアプリを開きました。内容を確認して送信してください。" : "入力内容は保存されず、メール作成画面に引き継がれます。"}</p></form></section>
    <footer><a href="#top" className="brand"><span className="brand-mark"><YkMark/></span><b>YUKE</b></a><p>© 2026 YUKE / 個人開発エンジニア</p><div className="social-mini">{socials.map((item)=><a key={item.kind} href={item.url} target="_blank" rel="noreferrer" aria-label={`${item.label}を開く`}><SocialIcon kind={item.kind}/></a>)}</div></footer>
  </main></>;
}
